### ISSUE TITLE
How to get access to Flexy Layout controller's blocks array?

### ISSUE THREAD

**Issue by muser83** [lorenzofox3/flexy-layout#12]
Hello

I want to print with json the current structure of the Flexy layout from my app. How can get it done?

**Comment by lorenzofox3** [comment]
Hello there is not straightforward as the blocks array is in a [private closure](https://github.com/lorenzofox3/flexy-layout/blob/master/src/MediatorController.js#L7)

however you can change the code

``` javascript
var blocks=[];
```

by 

``` javascript
var blocks=this.blocks=[];
```

so that the blocks are available on the controller ctrl.blocks

Laurent

**Comment by muser83** [comment]
Ok I have added a method to expose blocks property in flexyLayout controller like this:

```
            this.getBlocks = function() {
                return blocks;
            };
```

But... How can I call getBlocks from my app controller or from another directive?
I am a newbie in AngularJS... Sorry

I have tried this, but launches a flexylayout controller not found error:

```
    angular.module('controlRoom').directive('flexyLayoutDebugger', function() {
        return {
            restrict: 'A',
            require: '^flexyLayout',
            link: function(scope,element,attrs, flexyLayoutCtrl) {

                element.bind("mouseenter", function(){
                    console.log(flexyLayoutCtrl.getBlocks());
                });
            }
        }
    });
```

**Comment by lorenzofox3** [comment]
require:'^anyController'

imply that your directive expect to find a parent ont the dom tree which
has the anyController directive attached (refer to
documentationhttp://docs.angularjs.org/guide/directive
)

so <flexy-layout>
...
   <div flexy-layout-debugger></div>
...
</flexy-layout>

will works when
<flexy-layout>
</flexy-layout>

<div flexy-layout-debugger></div>

will throw Exception

Laurent

**Comment by muser83** [comment]
Yes, that was it!
Thank you!
