### ISSUE TITLE
CSS Conflicts with Twitter Bootstrap's

### ISSUE THREAD

**Issue by akarelas** [lorenzofox3/flexy-layout#2]
You use a CSS class called "row"

Bootstrap also uses "row", and furthermore puts margin: -20px to it, so the result is pretty ugly. Try orientation="vertical" and see.

The solution shouldn't be for bootstrap to change its class name, since bootstrap's "row" class is typed by users and is meant to be short and easy to remember.

The solution is for Flexy Layout to change its classname to something like flexy-row, since no user is required to remember that classname.

For now I'll fix it manually, but please fix in the distribution as well.

Thanks,

**Comment by lorenzofox3** [comment]
fix with 1687b71342e077b28b846564fec774b0de60e6b1
